### ISSUE TITLE
Something's wrong :(

### ISSUE THREAD

**Issue by tearjeong** [spalmurray/wordle-bot#13]
when I run the bot it says "ModuleNotFoundError: No module named 'pymongo'" how can I fix this (i'm a huge newbie when it comes to python/coding sorry)

**Comment by spalmurray** [comment]
Hey @tlkws !

Sounds like you don't have the pymongo package available for Python to use. You can install it using pip- here is a link to the installation instructions: [https://pymongo.readthedocs.io/en/stable/installation.html](https://pymongo.readthedocs.io/en/stable/installation.html)

Let me know if you are still having issues, I'm happy to help!

**Comment by tearjeong** [comment]
Hi! thank you for replying

now it says ModuleNotFoundError: No module named 'configuration'

tbh I'm trying to tweak your code to have it work for world like games named SUTOM and TUSMO

this is how they present: 
![IMG_6630](https://user-images.githubusercontent.com/103093162/162544050-4ce20f8c-bd2b-45fb-8894-2e89d5533614.jpg)

![IMG_6631](https://user-images.githubusercontent.com/103093162/162544044-df6bd6ee-adab-4e78-b08a-3664eab53041.jpg)

I am guessing I need to change what word the bot detects as it probably detects "wordle" for now
I'm also guessing it has to be around here : 
`if re.match(r"Wordle [0-9]+ [1-6|X]/6", message.content) is not None:`

But I am not 100% sure nor do I know how to make it work for two keywords

**Comment by spalmurray** [comment]
Check out this pull request someone made a while back. They added support for a number of other games, you can check out how exactly they did it. 

[https://github.com/spalmurray/wordle-bot/pull/7](https://github.com/spalmurray/wordle-bot/pull/7)
