### ISSUE TITLE
Wordle Bot down? Possibly after using !wb missing command.

### ISSUE THREAD

**Issue by riceonyou** [spalmurray/wordle-bot#18]
Hi. It seems that wordle bot went down after i tried using the !wb missing command. Don't know if you are already notified, but if not I made this issue. Also maybe the !wb missing can cause an error...

Thanks for creating the bot! It is really fun to track our wordles.

**Comment by spalmurray** [comment]
Hey @riceonyou !

I really appreciate the note! I have no idea why this happened, but I restarted the bot a few hours ago. Should be good now. Please let me know if this happens again! I don't have time to look into fixing this right now, but if it becomes a more prevalent issue I'll definitely take a look.

Glad you're enjoying the bot! As long as people keep using it, I'll keep it up and running :smile:
