### ISSUE TITLE
Reset score

### ISSUE THREAD

**Issue by vivianig** [spalmurray/wordle-bot#2]
Any chance it'd be possible to add a command to reset your own score?

**Comment by spalmurray** [comment]
Absolutely! I will implement this when I have some time over the next couple days. 

Thank you for the suggestion @vivianig !

**Comment by spalmurray** [comment]
Resolved by [this commit](https://github.com/spalmurray/wordle-bot/commit/b020dec9bb2a431f44aedd18c77f9154f5bcd42b) !
