### ISSUE TITLE
wordle-bot doesn't recognize Wordles with commas (1,000+)

### ISSUE THREAD

**Issue by pyretech** [spalmurray/wordle-bot#20]
Workaround is to delete the comma when posting but it'd be nice to have it work out-of-the-box.

**Comment by catpay** [comment]
> Workaround is to delete the comma when posting

Thank you for the workaround! I’m in a server that would also love a fix!

**Comment by j1mmie** [comment]
Fix available in #19

**Comment by j1mmie** [comment]
@spalmurray any chance we can get eyes on PR #19 and subsequently redeploy? Let me know if I can provide any help in any way

**Comment by spalmurray** [comment]
Hey all! I'm so sorry I never saw this. Only reason I checked on this repo is because I just noticed the bot is offline. I'll merge the PR and try to get a redeploy done.

**Comment by spalmurray** [comment]
PR is merged and I've redeployed the bot! Again, so sorry for any inconvenience here. Will try to get notifications for this repo working :heart:
